name: Publish docker image 

on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fuzzy-broccoli:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7

